# Модуль 7
Лог service_main для иллюстрации работы circuit_breaker

## service_main

2023-05-22 13:52:13 INFO:     Will watch for changes in these directories: ['/']
2023-05-22 13:52:13 INFO:     Uvicorn running on http://0.0.0.0:8083 (Press CTRL+C to quit)
2023-05-22 13:52:13 INFO:     Started reloader process [1] using WatchFiles
2023-05-22 13:52:14 INFO:     Started server process [9]
2023-05-22 13:52:14 INFO:     Waiting for application startup.
2023-05-22 13:52:14 INFO:     Application startup complete.
2023-05-22 13:52:15 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:15 WARNING:root:
2023-05-22 13:52:16 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:16 WARNING:root:
2023-05-22 13:52:17 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:17 WARNING:root:
2023-05-22 13:52:18 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:18 WARNING:root:
2023-05-22 13:52:19 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:19 WARNING:root:
2023-05-22 13:52:20 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:20 WARNING:root:
2023-05-22 13:52:21 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:21 WARNING:root:
2023-05-22 13:52:22 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:22 WARNING:root:
2023-05-22 13:52:23 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:23 WARNING:root:
2023-05-22 13:52:24 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:24 WARNING:root:
2023-05-22 13:52:25 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:25 WARNING:root:
2023-05-22 13:52:26 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:26 WARNING:root:
2023-05-22 13:52:27 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:27 WARNING:root:
2023-05-22 13:52:28 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:28 WARNING:root:
2023-05-22 13:52:29 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:29 WARNING:root:
2023-05-22 13:52:30 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:30 WARNING:root:
2023-05-22 13:52:31 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:31 WARNING:root:
2023-05-22 13:52:32 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:32 WARNING:root:
2023-05-22 13:52:33 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:33 WARNING:root:
2023-05-22 13:52:34 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:34 WARNING:root:
2023-05-22 13:52:35 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:35 WARNING:root:
2023-05-22 13:52:36 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:36 WARNING:root:
2023-05-22 13:52:37 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:37 WARNING:root:
2023-05-22 13:52:38 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:38 WARNING:root:
2023-05-22 13:52:39 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:39 WARNING:root:
2023-05-22 13:52:40 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:40 WARNING:root:
2023-05-22 13:52:41 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:41 WARNING:root:
2023-05-22 13:52:42 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:42 WARNING:root:
2023-05-22 13:52:43 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:43 WARNING:root:
2023-05-22 13:52:44 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:44 WARNING:root:
2023-05-22 13:52:45 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:45 WARNING:root:
2023-05-22 13:52:46 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:46 WARNING:root:
2023-05-22 13:52:47 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:47 WARNING:root:
2023-05-22 13:52:48 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:48 WARNING:root:
2023-05-22 13:52:49 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:49 WARNING:root:
2023-05-22 13:52:50 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:50 WARNING:root:
2023-05-22 13:52:51 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:51 WARNING:root:
2023-05-22 13:52:52 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:52 WARNING:root:
2023-05-22 13:52:53 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:53 WARNING:root:
2023-05-22 13:52:54 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:54 WARNING:root:
2023-05-22 13:52:55 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:55 WARNING:root:
2023-05-22 13:52:56 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:56 WARNING:root:
2023-05-22 13:52:57 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:57 WARNING:root:
2023-05-22 13:52:58 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:58 WARNING:root:
2023-05-22 13:52:59 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:52:59 WARNING:root:
2023-05-22 13:53:00 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:00 WARNING:root:
2023-05-22 13:53:01 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:01 WARNING:root:
2023-05-22 13:53:02 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:02 WARNING:root:
2023-05-22 13:53:04 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:04 WARNING:root:
2023-05-22 13:53:05 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:05 WARNING:root:
2023-05-22 13:53:06 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:06 WARNING:root:
2023-05-22 13:53:07 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:07 WARNING:root:
2023-05-22 13:53:08 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:08 WARNING:root:
2023-05-22 13:53:09 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:09 WARNING:root:
2023-05-22 13:53:10 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:10 WARNING:root:
2023-05-22 13:53:11 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:11 WARNING:root:
2023-05-22 13:53:12 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:12 WARNING:root:
2023-05-22 13:53:13 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:13 WARNING:root:
2023-05-22 13:53:14 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:14 WARNING:root:
2023-05-22 13:53:15 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:15 WARNING:root:
2023-05-22 13:53:16 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:16 WARNING:root:
2023-05-22 13:53:17 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:17 WARNING:root:
2023-05-22 13:53:18 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:18 WARNING:root:
2023-05-22 13:53:19 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:19 WARNING:root:
2023-05-22 13:53:20 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:20 WARNING:root:
2023-05-22 13:53:21 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:21 WARNING:root:
2023-05-22 13:53:22 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:22 WARNING:root:
2023-05-22 13:53:23 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:23 WARNING:root:
2023-05-22 13:53:24 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:24 WARNING:root:
2023-05-22 13:53:25 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:25 WARNING:root:
2023-05-22 13:53:26 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:26 WARNING:root:
2023-05-22 13:53:27 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:27 WARNING:root:
2023-05-22 13:53:28 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:28 WARNING:root:
2023-05-22 13:53:29 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:29 WARNING:root:
2023-05-22 13:53:30 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:30 WARNING:root:
2023-05-22 13:53:31 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:31 WARNING:root:
2023-05-22 13:53:32 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:32 WARNING:root:
2023-05-22 13:53:33 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:33 WARNING:root:
2023-05-22 13:53:34 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:34 WARNING:root:
2023-05-22 13:53:35 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:35 WARNING:root:
2023-05-22 13:53:36 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:36 WARNING:root:
2023-05-22 13:53:37 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:37 WARNING:root:
2023-05-22 13:53:38 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:38 WARNING:root:
2023-05-22 13:53:39 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:39 WARNING:root:
2023-05-22 13:53:40 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:40 WARNING:root:
2023-05-22 13:53:41 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:41 WARNING:root:
2023-05-22 13:53:42 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:42 WARNING:root:
2023-05-22 13:53:43 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:43 WARNING:root:
2023-05-22 13:53:44 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:44 WARNING:root:
2023-05-22 13:53:45 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:45 WARNING:root:
2023-05-22 13:53:46 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:46 WARNING:root:
2023-05-22 13:53:47 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:47 WARNING:root:
2023-05-22 13:53:48 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:48 WARNING:root:
2023-05-22 13:53:49 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:49 WARNING:root:
2023-05-22 13:53:50 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:50 WARNING:root:
2023-05-22 13:53:51 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:51 WARNING:root:
2023-05-22 13:53:52 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:52 WARNING:root:
2023-05-22 13:53:53 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:53 WARNING:root:
2023-05-22 13:53:54 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:54 WARNING:root:
2023-05-22 13:53:55 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:55 WARNING:root:
2023-05-22 13:53:56 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:56 WARNING:root:
2023-05-22 13:53:57 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:57 WARNING:root:
2023-05-22 13:53:58 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:58 WARNING:root:
2023-05-22 13:53:59 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:53:59 WARNING:root:
2023-05-22 13:54:00 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:00 WARNING:root:
2023-05-22 13:54:01 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:01 WARNING:root:
2023-05-22 13:54:02 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:02 WARNING:root:
2023-05-22 13:54:03 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:03 WARNING:root:
2023-05-22 13:54:04 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:04 WARNING:root:
2023-05-22 13:54:05 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:05 WARNING:root:
2023-05-22 13:54:06 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:06 WARNING:root:
2023-05-22 13:54:07 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:07 WARNING:root:
2023-05-22 13:54:08 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:08 WARNING:root:
2023-05-22 13:54:09 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:09 WARNING:root:
2023-05-22 13:54:10 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:10 WARNING:root:
2023-05-22 13:54:11 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:11 WARNING:root:
2023-05-22 13:54:12 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:12 WARNING:root:
2023-05-22 13:54:13 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:13 WARNING:root:
2023-05-22 13:54:14 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:14 WARNING:root:
2023-05-22 13:54:15 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:15 WARNING:root:
2023-05-22 13:54:16 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:16 WARNING:root:
2023-05-22 13:54:17 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:17 WARNING:root:
2023-05-22 13:54:18 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:18 WARNING:root:
2023-05-22 13:54:19 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:19 WARNING:root:
2023-05-22 13:54:20 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:20 WARNING:root:
2023-05-22 13:54:21 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:21 WARNING:root:
2023-05-22 13:54:22 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:22 WARNING:root:
2023-05-22 13:54:23 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:23 WARNING:root:
2023-05-22 13:54:24 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:24 WARNING:root:
2023-05-22 13:54:25 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:25 WARNING:root:
2023-05-22 13:54:26 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:26 WARNING:root:
2023-05-22 13:54:27 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:27 WARNING:root:
2023-05-22 13:54:28 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:28 WARNING:root:
2023-05-22 13:54:29 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:29 WARNING:root:
2023-05-22 13:54:30 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:30 WARNING:root:
2023-05-22 13:54:31 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:31 WARNING:root:
2023-05-22 13:54:32 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:32 WARNING:root:
2023-05-22 13:54:33 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:33 WARNING:root:
2023-05-22 13:54:34 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:34 WARNING:root:
2023-05-22 13:54:35 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:35 WARNING:root:
2023-05-22 13:54:36 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:36 WARNING:root:
2023-05-22 13:54:37 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:37 WARNING:root:
2023-05-22 13:54:38 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:38 WARNING:root:
2023-05-22 13:54:39 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:39 WARNING:root:
2023-05-22 13:54:40 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:40 WARNING:root:
2023-05-22 13:54:41 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:41 WARNING:root:
2023-05-22 13:54:42 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:42 WARNING:root:
2023-05-22 13:54:43 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:43 WARNING:root:
2023-05-22 13:54:44 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:44 WARNING:root:
2023-05-22 13:54:45 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:45 WARNING:root:
2023-05-22 13:54:46 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:46 WARNING:root:
2023-05-22 13:54:47 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:47 WARNING:root:
2023-05-22 13:54:48 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:48 WARNING:root:
2023-05-22 13:54:49 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:49 WARNING:root:
2023-05-22 13:54:50 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:50 WARNING:root:
2023-05-22 13:54:51 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:51 WARNING:root:
2023-05-22 13:54:52 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:52 WARNING:root:
2023-05-22 13:54:53 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:53 WARNING:root:
2023-05-22 13:54:54 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:54 WARNING:root:
2023-05-22 13:54:55 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:55 WARNING:root:
2023-05-22 13:54:56 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:56 WARNING:root:
2023-05-22 13:54:57 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:57 WARNING:root:
2023-05-22 13:54:58 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:58 WARNING:root:
2023-05-22 13:54:59 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:54:59 WARNING:root:
2023-05-22 13:55:00 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:00 WARNING:root:
2023-05-22 13:55:01 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:01 WARNING:root:
2023-05-22 13:55:02 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:02 WARNING:root:
2023-05-22 13:55:03 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:03 WARNING:root:
2023-05-22 13:55:04 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:04 WARNING:root:
2023-05-22 13:55:05 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:05 WARNING:root:
2023-05-22 13:55:06 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:06 WARNING:root:
2023-05-22 13:55:07 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:07 WARNING:root:
2023-05-22 13:55:08 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:08 WARNING:root:
2023-05-22 13:55:09 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:10 WARNING:root:
2023-05-22 13:55:11 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:11 WARNING:root:
2023-05-22 13:55:12 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:12 WARNING:root:
2023-05-22 13:55:13 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:13 WARNING:root:
2023-05-22 13:55:14 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:14 WARNING:root:
2023-05-22 13:55:15 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:15 WARNING:root:
2023-05-22 13:55:16 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:16 WARNING:root:
2023-05-22 13:55:17 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:17 WARNING:root:
2023-05-22 13:55:18 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:18 WARNING:root:
2023-05-22 13:55:19 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:19 WARNING:root:
2023-05-22 13:55:20 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:20 WARNING:root:
2023-05-22 13:55:21 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:21 WARNING:root:
2023-05-22 13:55:22 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:22 WARNING:root:
2023-05-22 13:55:23 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:23 WARNING:root:
2023-05-22 13:55:24 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:24 WARNING:root:
2023-05-22 13:55:25 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:25 WARNING:root:
2023-05-22 13:55:26 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:26 WARNING:root:
2023-05-22 13:55:27 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:27 WARNING:root:
2023-05-22 13:55:28 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:28 WARNING:root:
2023-05-22 13:55:29 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:29 WARNING:root:
2023-05-22 13:55:30 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:30 WARNING:root:
2023-05-22 13:56:01 Moore
2023-05-22 13:56:01 INFO:     172.18.0.1:35244 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:56:07 Moore
2023-05-22 13:55:31 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:31 WARNING:root:
2023-05-22 13:55:32 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:32 WARNING:root:
2023-05-22 13:55:33 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:33 WARNING:root:
2023-05-22 13:55:34 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:34 WARNING:root:
2023-05-22 13:55:35 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:35 WARNING:root:
2023-05-22 13:55:36 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:36 WARNING:root:
2023-05-22 13:55:37 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:37 WARNING:root:
2023-05-22 13:55:38 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:38 WARNING:root:
2023-05-22 13:55:39 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:39 WARNING:root:
2023-05-22 13:55:40 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:40 WARNING:root:
2023-05-22 13:55:41 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:41 WARNING:root:
2023-05-22 13:55:42 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:42 WARNING:root:
2023-05-22 13:55:43 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:43 WARNING:root:
2023-05-22 13:55:44 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:44 WARNING:root:
2023-05-22 13:55:45 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:45 WARNING:root:
2023-05-22 13:55:46 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:46 WARNING:root:
2023-05-22 13:55:47 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:47 WARNING:root:
2023-05-22 13:55:48 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:48 WARNING:root:
2023-05-22 13:55:49 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:49 WARNING:root:
2023-05-22 13:55:50 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:50 WARNING:root:
2023-05-22 13:55:51 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:51 WARNING:root:
2023-05-22 13:55:52 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:52 WARNING:root:
2023-05-22 13:55:53 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:53 WARNING:root:
2023-05-22 13:55:54 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:54 WARNING:root:
2023-05-22 13:55:55 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:55 WARNING:root:
2023-05-22 13:55:56 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:56 WARNING:root:
2023-05-22 13:55:57 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:57 WARNING:root:
2023-05-22 13:55:58 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:58 WARNING:root:
2023-05-22 13:55:59 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:55:59 WARNING:root:
2023-05-22 13:56:00 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:00 WARNING:root:
2023-05-22 13:56:01 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:01 WARNING:root:
2023-05-22 13:56:02 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:02 WARNING:root:
2023-05-22 13:56:03 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:03 WARNING:root:
2023-05-22 13:56:04 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:04 WARNING:root:
2023-05-22 13:56:05 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:05 WARNING:root:
2023-05-22 13:56:06 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:06 WARNING:root:
2023-05-22 13:56:07 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:07 WARNING:root:
2023-05-22 13:56:08 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:08 WARNING:root:
2023-05-22 13:56:09 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:09 WARNING:root:
2023-05-22 13:56:10 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:10 WARNING:root:
2023-05-22 13:56:11 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:11 WARNING:root:
2023-05-22 13:56:12 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:12 WARNING:root:
2023-05-22 13:56:13 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:13 WARNING:root:
2023-05-22 13:56:14 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:14 WARNING:root:
2023-05-22 13:56:15 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:15 WARNING:root:
2023-05-22 13:56:16 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:16 WARNING:root:
2023-05-22 13:56:17 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:17 WARNING:root:
2023-05-22 13:56:18 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:18 WARNING:root:
2023-05-22 13:56:19 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:19 WARNING:root:
2023-05-22 13:56:20 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:20 WARNING:root:
2023-05-22 13:56:21 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:21 WARNING:root:
2023-05-22 13:56:22 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:22 WARNING:root:
2023-05-22 13:56:23 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:23 WARNING:root:
2023-05-22 13:56:24 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:24 WARNING:root:
2023-05-22 13:56:25 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:25 WARNING:root:
2023-05-22 13:56:26 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:26 WARNING:root:
2023-05-22 13:56:27 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:27 WARNING:root:
2023-05-22 13:56:28 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:28 WARNING:root:
2023-05-22 13:56:29 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:29 WARNING:root:
2023-05-22 13:56:30 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:30 WARNING:root:
2023-05-22 13:56:31 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:31 WARNING:root:
2023-05-22 13:56:32 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:32 WARNING:root:
2023-05-22 13:56:33 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:33 WARNING:root:
2023-05-22 13:56:34 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:34 WARNING:root:
2023-05-22 13:56:35 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:35 WARNING:root:
2023-05-22 13:56:36 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:36 WARNING:root:
2023-05-22 13:56:07 INFO:     172.18.0.1:35252 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:56:12 Moore
2023-05-22 13:56:12 INFO:     172.18.0.1:35260 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:56:37 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:37 WARNING:root:
2023-05-22 13:56:38 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:38 WARNING:root:
2023-05-22 13:56:39 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:39 WARNING:root:
2023-05-22 13:56:40 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:40 WARNING:root:
2023-05-22 13:56:41 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:41 WARNING:root:
2023-05-22 13:56:42 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:42 WARNING:root:
2023-05-22 13:56:43 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:43 WARNING:root:
2023-05-22 13:56:44 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:44 WARNING:root:
2023-05-22 13:56:45 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:45 WARNING:root:
2023-05-22 13:56:46 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:46 WARNING:root:
2023-05-22 13:56:47 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:47 WARNING:root:
2023-05-22 13:56:48 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:48 WARNING:root:
2023-05-22 13:56:49 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:49 WARNING:root:
2023-05-22 13:56:50 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:50 WARNING:root:
2023-05-22 13:56:51 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:51 WARNING:root:
2023-05-22 13:56:52 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:52 WARNING:root:
2023-05-22 13:56:53 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:53 WARNING:root:
2023-05-22 13:56:54 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:54 WARNING:root:
2023-05-22 13:56:55 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:55 WARNING:root:
2023-05-22 13:56:56 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:56 WARNING:root:
2023-05-22 13:56:57 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:57 WARNING:root:
2023-05-22 13:56:58 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:58 WARNING:root:
2023-05-22 13:56:59 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:56:59 WARNING:root:
2023-05-22 13:57:00 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:00 WARNING:root:
2023-05-22 13:57:01 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:01 WARNING:root:
2023-05-22 13:57:02 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:02 WARNING:root:
2023-05-22 13:57:03 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:03 WARNING:root:
2023-05-22 13:57:04 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:04 WARNING:root:
2023-05-22 13:57:05 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:05 WARNING:root:
2023-05-22 13:57:06 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:06 WARNING:root:
2023-05-22 13:57:07 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:07 WARNING:root:
2023-05-22 13:57:08 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:08 WARNING:root:
2023-05-22 13:57:09 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:09 WARNING:root:
2023-05-22 13:57:10 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:10 WARNING:root:
2023-05-22 13:57:11 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:11 WARNING:root:
2023-05-22 13:57:12 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:13 WARNING:root:
2023-05-22 13:57:14 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:14 WARNING:root:
2023-05-22 13:57:15 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:15 WARNING:root:
2023-05-22 13:57:16 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:16 WARNING:root:
2023-05-22 13:57:17 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:17 WARNING:root:
2023-05-22 13:57:18 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:18 WARNING:root:
2023-05-22 13:57:19 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:19 WARNING:root:
2023-05-22 13:57:20 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:20 WARNING:root:
2023-05-22 13:57:21 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:21 WARNING:root:
2023-05-22 13:57:22 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:22 WARNING:root:
2023-05-22 13:57:23 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:23 WARNING:root:
2023-05-22 13:57:24 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:24 WARNING:root:
2023-05-22 13:57:25 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:25 WARNING:root:
2023-05-22 13:57:26 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:26 WARNING:root:
2023-05-22 13:57:27 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:27 WARNING:root:
2023-05-22 13:57:28 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:28 WARNING:root:
2023-05-22 13:57:29 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:29 WARNING:root:
2023-05-22 13:57:30 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:30 WARNING:root:
2023-05-22 13:57:31 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:31 WARNING:root:
2023-05-22 13:57:32 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:32 WARNING:root:
2023-05-22 13:57:33 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:33 WARNING:root:
2023-05-22 13:57:34 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:34 WARNING:root:
2023-05-22 13:57:35 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:35 WARNING:root:
2023-05-22 13:57:36 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:36 WARNING:root:
2023-05-22 13:57:37 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:37 WARNING:root:
2023-05-22 13:57:38 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:38 WARNING:root:
2023-05-22 13:57:39 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:39 WARNING:root:
2023-05-22 13:57:40 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:40 WARNING:root:
2023-05-22 13:57:41 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:41 WARNING:root:
2023-05-22 13:57:42 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:42 WARNING:root:
2023-05-22 13:57:43 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:43 WARNING:root:
2023-05-22 13:57:44 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:44 WARNING:root:
2023-05-22 13:57:45 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:45 WARNING:root:
2023-05-22 13:57:46 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:46 WARNING:root:
2023-05-22 13:57:47 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:47 WARNING:root:
2023-05-22 13:57:48 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:48 WARNING:root:
2023-05-22 13:57:49 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:49 WARNING:root:
2023-05-22 13:57:50 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:50 WARNING:root:
2023-05-22 13:57:51 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:51 WARNING:root:
2023-05-22 13:57:52 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:52 WARNING:root:
2023-05-22 13:57:53 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:53 WARNING:root:
2023-05-22 13:57:54 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:54 WARNING:root:
2023-05-22 13:57:55 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:01 Moore
2023-05-22 13:58:01 INFO:     172.18.0.1:35268 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:58:03 Moore
2023-05-22 13:58:03 INFO:     172.18.0.1:35276 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:57:55 WARNING:root:
2023-05-22 13:57:56 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:56 WARNING:root:
2023-05-22 13:57:57 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:57 WARNING:root:
2023-05-22 13:57:58 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:58 WARNING:root:
2023-05-22 13:57:59 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:57:59 WARNING:root:
2023-05-22 13:58:00 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:00 WARNING:root:
2023-05-22 13:58:01 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:01 WARNING:root:
2023-05-22 13:58:02 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:02 WARNING:root:
2023-05-22 13:58:03 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:03 WARNING:root:
2023-05-22 13:58:04 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:04 WARNING:root:
2023-05-22 13:58:05 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:05 WARNING:root:
2023-05-22 13:58:06 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:06 WARNING:root:
2023-05-22 13:58:07 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:07 WARNING:root:
2023-05-22 13:58:08 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:08 WARNING:root:
2023-05-22 13:58:09 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:09 WARNING:root:
2023-05-22 13:58:10 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:10 WARNING:root:
2023-05-22 13:58:11 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:11 WARNING:root:
2023-05-22 13:58:12 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:12 WARNING:root:
2023-05-22 13:58:13 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:13 WARNING:root:
2023-05-22 13:58:14 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:14 WARNING:root:
2023-05-22 13:58:15 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:15 WARNING:root:
2023-05-22 13:58:16 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:16 WARNING:root:
2023-05-22 13:58:17 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:17 WARNING:root:
2023-05-22 13:58:18 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:18 WARNING:root:
2023-05-22 13:58:19 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:19 WARNING:root:
2023-05-22 13:58:20 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:20 WARNING:root:
2023-05-22 13:58:21 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:21 WARNING:root:
2023-05-22 13:58:22 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:22 WARNING:root:
2023-05-22 13:58:23 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:23 WARNING:root:
2023-05-22 13:58:24 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:24 WARNING:root:
2023-05-22 13:58:25 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:25 WARNING:root:
2023-05-22 13:58:26 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:26 WARNING:root:
2023-05-22 13:58:27 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:27 WARNING:root:
2023-05-22 13:58:28 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:28 WARNING:root:
2023-05-22 13:58:29 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:29 WARNING:root:
2023-05-22 13:58:30 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:30 WARNING:root:
2023-05-22 13:58:31 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:31 WARNING:root:
2023-05-22 13:58:32 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:32 WARNING:root:
2023-05-22 13:58:33 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:33 WARNING:root:
2023-05-22 13:58:34 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 13:58:34 WARNING:root:
2023-05-22 13:58:22 Moore
2023-05-22 13:58:22 INFO:     172.18.0.1:35284 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:58:35 --- Logging error ---
2023-05-22 13:58:35 Traceback (most recent call last):
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
2023-05-22 13:58:35     conn = connection.create_connection(
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
2023-05-22 13:58:35     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-05-22 13:58:35   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-05-22 13:58:35     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-05-22 13:58:35 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-05-22 13:58:35 
2023-05-22 13:58:35 During handling of the above exception, another exception occurred:
2023-05-22 13:58:35 
2023-05-22 13:58:35 Traceback (most recent call last):
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-05-22 13:58:35     httplib_response = self._make_request(
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2023-05-22 13:58:35     conn.request(method, url, **httplib_request_kw)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
2023-05-22 13:58:35     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-05-22 13:58:35   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2023-05-22 13:58:35     self._send_request(method, url, body, headers, encode_chunked)
2023-05-22 13:58:35   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2023-05-22 13:58:35     self.endheaders(body, encode_chunked=encode_chunked)
2023-05-22 13:58:35   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2023-05-22 13:58:35     self._send_output(message_body, encode_chunked=encode_chunked)
2023-05-22 13:58:35   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2023-05-22 13:58:35     self.send(msg)
2023-05-22 13:58:35   File "/usr/lib/python3.10/http/client.py", line 975, in send
2023-05-22 13:58:35     self.connect()
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
2023-05-22 13:58:35     conn = self._new_conn()
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
2023-05-22 13:58:35     raise NewConnectionError(
2023-05-22 13:58:35 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3a2547eec0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2023-05-22 13:58:35 
2023-05-22 13:58:35 During handling of the above exception, another exception occurred:
2023-05-22 13:58:35 
2023-05-22 13:58:35 Traceback (most recent call last):
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2023-05-22 13:58:35     resp = conn.urlopen(
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-05-22 13:58:35     retries = retries.increment(
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
2023-05-22 13:58:35     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-05-22 13:58:35 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a2547eec0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:58:35 
2023-05-22 13:58:35 During handling of the above exception, another exception occurred:
2023-05-22 13:58:35 
2023-05-22 13:58:35 Traceback (most recent call last):
2023-05-22 13:58:35   File "/./service_main.py", line 74, in get_author
2023-05-22 13:58:35     response_author = requests.get("http://" + service_author + "/authors/" + str(id))
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
2023-05-22 13:58:35     return request("get", url, params=params, **kwargs)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
2023-05-22 13:58:35     return session.request(method=method, url=url, **kwargs)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2023-05-22 13:58:35     resp = self.send(prep, **send_kwargs)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2023-05-22 13:58:35     r = adapter.send(request, **kwargs)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
2023-05-22 13:58:35     raise ConnectionError(e, request=request)
2023-05-22 13:58:35 requests.exceptions.ConnectionError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a2547eec0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:58:35 
2023-05-22 13:58:35 During handling of the above exception, another exception occurred:
2023-05-22 13:58:35 
2023-05-22 13:58:35 Traceback (most recent call last):
2023-05-22 13:58:35   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
2023-05-22 13:58:35     msg = self.format(record)
2023-05-22 13:58:35   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
2023-05-22 13:58:35     return fmt.format(record)
2023-05-22 13:58:35   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
2023-05-22 13:58:35     record.message = record.getMessage()
2023-05-22 13:58:35   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
2023-05-22 13:58:35     msg = msg % self.args
2023-05-22 13:58:35 TypeError: not all arguments converted during string formatting
2023-05-22 13:58:35 Call stack:
2023-05-22 13:58:35   File "<string>", line 1, in <module>
2023-05-22 13:58:35   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2023-05-22 13:58:35     exitcode = _main(fd, parent_sentinel)
2023-05-22 13:58:35   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
2023-05-22 13:58:35     return self._bootstrap(parent_sentinel)
2023-05-22 13:58:35   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-05-22 13:58:35     self.run()
2023-05-22 13:58:35   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-05-22 13:58:35     self._target(*self._args, **self._kwargs)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-05-22 13:58:35     target(sockets=sockets)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
2023-05-22 13:58:35     return asyncio.run(self.serve(sockets=sockets))
2023-05-22 13:58:35   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2023-05-22 13:58:35     return loop.run_until_complete(main)
2023-05-22 13:58:35   File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
2023-05-22 13:58:35     self.run_forever()
2023-05-22 13:58:35   File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
2023-05-22 13:58:35     self._run_once()
2023-05-22 13:58:35   File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
2023-05-22 13:58:35     handle._run()
2023-05-22 13:58:35   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2023-05-22 13:58:35     self._context.run(self._callback, *self._args)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-05-22 13:58:35     result = await app(  # type: ignore[func-returns-value]
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-22 13:58:35     return await self.app(scope, receive, send)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
2023-05-22 13:58:35     await super().__call__(scope, receive, send)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
2023-05-22 13:58:35     await self.middleware_stack(scope, receive, send)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-22 13:58:35     await self.app(scope, receive, _send)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-22 13:58:35     await self.app(scope, receive, sender)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-22 13:58:35     await self.app(scope, receive, send)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
2023-05-22 13:58:35     await route.handle(scope, receive, send)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-05-22 13:58:35     await self.app(scope, receive, send)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
2023-05-22 13:58:35     response = await func(request)
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
2023-05-22 13:58:35     raw_response = await run_endpoint_function(
2023-05-22 13:58:35   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-22 13:58:35     return await dependant.call(**values)
2023-05-22 13:58:35   File "/./service_main.py", line 105, in read_presentation
2023-05-22 13:58:35     author = get_author(presentation.author_id)
2023-05-22 13:58:35   File "/./circuitbreaker.py", line 159, in wrapper
2023-05-22 13:58:35     return call(function, *args, **kwargs)
2023-05-22 13:58:35   File "/./circuitbreaker.py", line 170, in call
2023-05-22 13:58:35     return func(*args, **kwargs)
2023-05-22 13:58:35   File "/./service_main.py", line 76, in get_author
2023-05-22 13:58:35     logging.warning(">>> Error Connecting:", errc)
2023-05-22 13:58:35 Message: '>>> Error Connecting:'
2023-05-22 13:58:35 Arguments: (ConnectionError(MaxRetryError("HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a2547eec0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")),)
2023-05-22 13:58:35 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:35 WARNING:root:
2023-05-22 13:58:36 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:36 WARNING:root:
2023-05-22 13:58:37 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:37 WARNING:root:
2023-05-22 13:58:35 INFO:     172.18.0.1:35292 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 500 Internal Server Error
2023-05-22 13:58:38 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:38 WARNING:root:
2023-05-22 13:58:39 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:39 WARNING:root:
2023-05-22 13:58:40 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:40 WARNING:root:
2023-05-22 13:58:41 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:41 WARNING:root:
2023-05-22 13:58:42 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:42 WARNING:root:
2023-05-22 13:58:43 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:43 WARNING:root:
2023-05-22 13:58:44 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:44 WARNING:root:
2023-05-22 13:58:45 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:45 WARNING:root:
2023-05-22 13:58:46 WARNING:root:Circuit "get_author" is "closed", failures: 1
2023-05-22 13:58:46 WARNING:root:
2023-05-22 13:58:47 --- Logging error ---
2023-05-22 13:58:47 Traceback (most recent call last):
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
2023-05-22 13:58:47     conn = connection.create_connection(
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
2023-05-22 13:58:47     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-05-22 13:58:47   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-05-22 13:58:47     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-05-22 13:58:47 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-05-22 13:58:47 
2023-05-22 13:58:47 During handling of the above exception, another exception occurred:
2023-05-22 13:58:47 
2023-05-22 13:58:47 Traceback (most recent call last):
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-05-22 13:58:47     httplib_response = self._make_request(
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2023-05-22 13:58:47     conn.request(method, url, **httplib_request_kw)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
2023-05-22 13:58:47     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-05-22 13:58:47   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2023-05-22 13:58:47     self._send_request(method, url, body, headers, encode_chunked)
2023-05-22 13:58:47   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2023-05-22 13:58:47     self.endheaders(body, encode_chunked=encode_chunked)
2023-05-22 13:58:47   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2023-05-22 13:58:47     self._send_output(message_body, encode_chunked=encode_chunked)
2023-05-22 13:58:47   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2023-05-22 13:58:47     self.send(msg)
2023-05-22 13:58:47   File "/usr/lib/python3.10/http/client.py", line 975, in send
2023-05-22 13:58:47     self.connect()
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
2023-05-22 13:58:47     conn = self._new_conn()
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
2023-05-22 13:58:47     raise NewConnectionError(
2023-05-22 13:58:47 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3a24b88700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2023-05-22 13:58:47 
2023-05-22 13:58:47 During handling of the above exception, another exception occurred:
2023-05-22 13:58:47 
2023-05-22 13:58:47 Traceback (most recent call last):
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2023-05-22 13:58:47     resp = conn.urlopen(
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-05-22 13:58:47     retries = retries.increment(
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
2023-05-22 13:58:47     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-05-22 13:58:47 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b88700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:58:47 
2023-05-22 13:58:47 During handling of the above exception, another exception occurred:
2023-05-22 13:58:47 
2023-05-22 13:58:47 Traceback (most recent call last):
2023-05-22 13:58:47   File "/./service_main.py", line 74, in get_author
2023-05-22 13:58:47     response_author = requests.get("http://" + service_author + "/authors/" + str(id))
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
2023-05-22 13:58:47     return request("get", url, params=params, **kwargs)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
2023-05-22 13:58:47     return session.request(method=method, url=url, **kwargs)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2023-05-22 13:58:47     resp = self.send(prep, **send_kwargs)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2023-05-22 13:58:47     r = adapter.send(request, **kwargs)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
2023-05-22 13:58:47     raise ConnectionError(e, request=request)
2023-05-22 13:58:47 requests.exceptions.ConnectionError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b88700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:58:47 
2023-05-22 13:58:47 During handling of the above exception, another exception occurred:
2023-05-22 13:58:47 
2023-05-22 13:58:47 Traceback (most recent call last):
2023-05-22 13:58:47   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
2023-05-22 13:58:47     msg = self.format(record)
2023-05-22 13:58:47   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
2023-05-22 13:58:47     return fmt.format(record)
2023-05-22 13:58:47   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
2023-05-22 13:58:47     record.message = record.getMessage()
2023-05-22 13:58:47   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
2023-05-22 13:58:47     msg = msg % self.args
2023-05-22 13:58:47 TypeError: not all arguments converted during string formatting
2023-05-22 13:58:47 Call stack:
2023-05-22 13:58:47   File "<string>", line 1, in <module>
2023-05-22 13:58:47   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2023-05-22 13:58:47     exitcode = _main(fd, parent_sentinel)
2023-05-22 13:58:47   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
2023-05-22 13:58:47     return self._bootstrap(parent_sentinel)
2023-05-22 13:58:47   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-05-22 13:58:47     self.run()
2023-05-22 13:58:47   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-05-22 13:58:47 INFO:     172.18.0.1:35298 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 500 Internal Server Error
2023-05-22 13:58:47     self._target(*self._args, **self._kwargs)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-05-22 13:58:47     target(sockets=sockets)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
2023-05-22 13:58:47     return asyncio.run(self.serve(sockets=sockets))
2023-05-22 13:58:47   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2023-05-22 13:58:47     return loop.run_until_complete(main)
2023-05-22 13:58:47   File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
2023-05-22 13:58:47     self.run_forever()
2023-05-22 13:58:47   File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
2023-05-22 13:58:47     self._run_once()
2023-05-22 13:58:47   File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
2023-05-22 13:58:47     handle._run()
2023-05-22 13:58:47   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2023-05-22 13:58:47     self._context.run(self._callback, *self._args)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-05-22 13:58:47     result = await app(  # type: ignore[func-returns-value]
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-22 13:58:47     return await self.app(scope, receive, send)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
2023-05-22 13:58:47     await super().__call__(scope, receive, send)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
2023-05-22 13:58:47     await self.middleware_stack(scope, receive, send)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-22 13:58:47     await self.app(scope, receive, _send)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-22 13:58:47     await self.app(scope, receive, sender)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-22 13:58:47     await self.app(scope, receive, send)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
2023-05-22 13:58:47     await route.handle(scope, receive, send)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-05-22 13:58:47     await self.app(scope, receive, send)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
2023-05-22 13:58:47     response = await func(request)
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
2023-05-22 13:58:47     raw_response = await run_endpoint_function(
2023-05-22 13:58:47   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-22 13:58:47     return await dependant.call(**values)
2023-05-22 13:58:47   File "/./service_main.py", line 105, in read_presentation
2023-05-22 13:58:47     author = get_author(presentation.author_id)
2023-05-22 13:58:47   File "/./circuitbreaker.py", line 159, in wrapper
2023-05-22 13:58:47     return call(function, *args, **kwargs)
2023-05-22 13:58:47   File "/./circuitbreaker.py", line 170, in call
2023-05-22 13:58:47     return func(*args, **kwargs)
2023-05-22 13:58:47   File "/./service_main.py", line 76, in get_author
2023-05-22 13:58:47     logging.warning(">>> Error Connecting:", errc)
2023-05-22 13:58:47 Message: '>>> Error Connecting:'
2023-05-22 13:58:47 Arguments: (ConnectionError(MaxRetryError("HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b88700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")),)
2023-05-22 13:58:47 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:47 WARNING:root:
2023-05-22 13:58:48 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:48 WARNING:root:
2023-05-22 13:58:49 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:49 WARNING:root:
2023-05-22 13:58:50 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:50 WARNING:root:
2023-05-22 13:58:51 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:51 WARNING:root:
2023-05-22 13:58:52 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:52 WARNING:root:
2023-05-22 13:58:53 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:53 WARNING:root:
2023-05-22 13:58:54 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:54 WARNING:root:
2023-05-22 13:58:55 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:55 WARNING:root:
2023-05-22 13:58:56 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:56 WARNING:root:
2023-05-22 13:58:57 WARNING:root:Circuit "get_author" is "closed", failures: 2
2023-05-22 13:58:57 WARNING:root:
2023-05-22 13:58:58 --- Logging error ---
2023-05-22 13:58:58 Traceback (most recent call last):
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
2023-05-22 13:58:58     conn = connection.create_connection(
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
2023-05-22 13:58:58     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-05-22 13:58:58   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-05-22 13:58:58     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-05-22 13:58:58 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-05-22 13:58:58 
2023-05-22 13:58:58 During handling of the above exception, another exception occurred:
2023-05-22 13:58:58 
2023-05-22 13:58:58 Traceback (most recent call last):
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-05-22 13:58:58     httplib_response = self._make_request(
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2023-05-22 13:58:58     conn.request(method, url, **httplib_request_kw)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
2023-05-22 13:58:58     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-05-22 13:58:58   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2023-05-22 13:58:58     self._send_request(method, url, body, headers, encode_chunked)
2023-05-22 13:58:58   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2023-05-22 13:58:58     self.endheaders(body, encode_chunked=encode_chunked)
2023-05-22 13:58:58   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2023-05-22 13:58:58     self._send_output(message_body, encode_chunked=encode_chunked)
2023-05-22 13:58:58   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2023-05-22 13:58:58     self.send(msg)
2023-05-22 13:58:58   File "/usr/lib/python3.10/http/client.py", line 975, in send
2023-05-22 13:58:58     self.connect()
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
2023-05-22 13:58:58     conn = self._new_conn()
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
2023-05-22 13:58:58     raise NewConnectionError(
2023-05-22 13:58:58 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3a24b897e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2023-05-22 13:58:58 
2023-05-22 13:58:58 During handling of the above exception, another exception occurred:
2023-05-22 13:58:58 
2023-05-22 13:58:58 Traceback (most recent call last):
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2023-05-22 13:58:58     resp = conn.urlopen(
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-05-22 13:58:58     retries = retries.increment(
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
2023-05-22 13:58:58     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-05-22 13:58:58 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b897e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:58:58 
2023-05-22 13:58:58 During handling of the above exception, another exception occurred:
2023-05-22 13:58:58 
2023-05-22 13:58:58 Traceback (most recent call last):
2023-05-22 13:58:58   File "/./service_main.py", line 74, in get_author
2023-05-22 13:58:58     response_author = requests.get("http://" + service_author + "/authors/" + str(id))
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
2023-05-22 13:58:58     return request("get", url, params=params, **kwargs)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
2023-05-22 13:58:58     return session.request(method=method, url=url, **kwargs)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2023-05-22 13:58:58     resp = self.send(prep, **send_kwargs)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2023-05-22 13:58:58     r = adapter.send(request, **kwargs)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
2023-05-22 13:58:58     raise ConnectionError(e, request=request)
2023-05-22 13:58:58 requests.exceptions.ConnectionError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b897e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:58:58 
2023-05-22 13:58:58 During handling of the above exception, another exception occurred:
2023-05-22 13:58:58 
2023-05-22 13:58:58 Traceback (most recent call last):
2023-05-22 13:58:58   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
2023-05-22 13:58:58     msg = self.format(record)
2023-05-22 13:58:58   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
2023-05-22 13:58:58     return fmt.format(record)
2023-05-22 13:58:58   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
2023-05-22 13:58:58     record.message = record.getMessage()
2023-05-22 13:58:58   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
2023-05-22 13:58:58     msg = msg % self.args
2023-05-22 13:58:58 TypeError: not all arguments converted during string formatting
2023-05-22 13:58:58 Call stack:
2023-05-22 13:58:58   File "<string>", line 1, in <module>
2023-05-22 13:58:58   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2023-05-22 13:58:58     exitcode = _main(fd, parent_sentinel)
2023-05-22 13:58:58   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
2023-05-22 13:58:58     return self._bootstrap(parent_sentinel)
2023-05-22 13:58:58   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-05-22 13:58:58     self.run()
2023-05-22 13:58:58   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-05-22 13:58:58     self._target(*self._args, **self._kwargs)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-05-22 13:58:58     target(sockets=sockets)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
2023-05-22 13:58:58     return asyncio.run(self.serve(sockets=sockets))
2023-05-22 13:58:58   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2023-05-22 13:58:58     return loop.run_until_complete(main)
2023-05-22 13:58:58   File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
2023-05-22 13:58:58     self.run_forever()
2023-05-22 13:58:58   File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
2023-05-22 13:58:58     self._run_once()
2023-05-22 13:58:58   File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
2023-05-22 13:58:58     handle._run()
2023-05-22 13:58:58   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2023-05-22 13:58:58     self._context.run(self._callback, *self._args)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-05-22 13:58:58     result = await app(  # type: ignore[func-returns-value]
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-22 13:58:58     return await self.app(scope, receive, send)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
2023-05-22 13:58:58     await super().__call__(scope, receive, send)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
2023-05-22 13:58:58     await self.middleware_stack(scope, receive, send)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-22 13:58:58     await self.app(scope, receive, _send)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-22 13:58:58     await self.app(scope, receive, sender)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-22 13:58:58     await self.app(scope, receive, send)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
2023-05-22 13:58:58     await route.handle(scope, receive, send)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-05-22 13:58:58     await self.app(scope, receive, send)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
2023-05-22 13:58:58     response = await func(request)
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
2023-05-22 13:58:58     raw_response = await run_endpoint_function(
2023-05-22 13:58:58   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-22 13:58:58     return await dependant.call(**values)
2023-05-22 13:58:58   File "/./service_main.py", line 105, in read_presentation
2023-05-22 13:58:58     author = get_author(presentation.author_id)
2023-05-22 13:58:58   File "/./circuitbreaker.py", line 159, in wrapper
2023-05-22 13:58:58     return call(function, *args, **kwargs)
2023-05-22 13:58:58   File "/./circuitbreaker.py", line 170, in call
2023-05-22 13:58:58     return func(*args, **kwargs)
2023-05-22 13:58:58   File "/./service_main.py", line 76, in get_author
2023-05-22 13:58:58     logging.warning(">>> Error Connecting:", errc)
2023-05-22 13:58:58 Message: '>>> Error Connecting:'
2023-05-22 13:58:58 Arguments: (ConnectionError(MaxRetryError("HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b897e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")),)
2023-05-22 13:58:58 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:58:58 INFO:     172.18.0.1:35304 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 500 Internal Server Error
2023-05-22 13:58:58 WARNING:root:
2023-05-22 13:58:59 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:58:59 WARNING:root:
2023-05-22 13:59:00 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:00 WARNING:root:
2023-05-22 13:59:01 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:01 WARNING:root:
2023-05-22 13:59:02 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:02 WARNING:root:
2023-05-22 13:59:03 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:03 WARNING:root:
2023-05-22 13:59:04 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:04 WARNING:root:
2023-05-22 13:59:05 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:05 WARNING:root:
2023-05-22 13:59:06 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:06 WARNING:root:
2023-05-22 13:59:07 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:07 WARNING:root:
2023-05-22 13:59:08 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:08 WARNING:root:
2023-05-22 13:59:09 WARNING:root:Circuit "get_author" is "closed", failures: 3
2023-05-22 13:59:09 WARNING:root:
2023-05-22 13:59:10 --- Logging error ---
2023-05-22 13:59:10 Traceback (most recent call last):
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
2023-05-22 13:59:10     conn = connection.create_connection(
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
2023-05-22 13:59:10     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-05-22 13:59:10   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-05-22 13:59:10     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-05-22 13:59:10 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-05-22 13:59:10 
2023-05-22 13:59:10 During handling of the above exception, another exception occurred:
2023-05-22 13:59:10 
2023-05-22 13:59:10 Traceback (most recent call last):
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-05-22 13:59:10     httplib_response = self._make_request(
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2023-05-22 13:59:10     conn.request(method, url, **httplib_request_kw)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
2023-05-22 13:59:10     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-05-22 13:59:10   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2023-05-22 13:59:10     self._send_request(method, url, body, headers, encode_chunked)
2023-05-22 13:59:10   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2023-05-22 13:59:10     self.endheaders(body, encode_chunked=encode_chunked)
2023-05-22 13:59:10   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2023-05-22 13:59:10     self._send_output(message_body, encode_chunked=encode_chunked)
2023-05-22 13:59:10   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2023-05-22 13:59:10     self.send(msg)
2023-05-22 13:59:10   File "/usr/lib/python3.10/http/client.py", line 975, in send
2023-05-22 13:59:10     self.connect()
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
2023-05-22 13:59:10     conn = self._new_conn()
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
2023-05-22 13:59:10     raise NewConnectionError(
2023-05-22 13:59:10 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3a24b8a6b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2023-05-22 13:59:10 
2023-05-22 13:59:10 During handling of the above exception, another exception occurred:
2023-05-22 13:59:10 
2023-05-22 13:59:10 Traceback (most recent call last):
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2023-05-22 13:59:10     resp = conn.urlopen(
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-05-22 13:59:10     retries = retries.increment(
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
2023-05-22 13:59:10     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-05-22 13:59:10 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b8a6b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:59:10 
2023-05-22 13:59:10 During handling of the above exception, another exception occurred:
2023-05-22 13:59:10 
2023-05-22 13:59:10 Traceback (most recent call last):
2023-05-22 13:59:10   File "/./service_main.py", line 74, in get_author
2023-05-22 13:59:10     response_author = requests.get("http://" + service_author + "/authors/" + str(id))
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
2023-05-22 13:59:10     return request("get", url, params=params, **kwargs)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
2023-05-22 13:59:10     return session.request(method=method, url=url, **kwargs)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2023-05-22 13:59:10     resp = self.send(prep, **send_kwargs)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2023-05-22 13:59:10     r = adapter.send(request, **kwargs)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
2023-05-22 13:59:10     raise ConnectionError(e, request=request)
2023-05-22 13:59:10 requests.exceptions.ConnectionError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b8a6b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:59:10 
2023-05-22 13:59:10 During handling of the above exception, another exception occurred:
2023-05-22 13:59:10 
2023-05-22 13:59:10 Traceback (most recent call last):
2023-05-22 13:59:10   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
2023-05-22 13:59:10     msg = self.format(record)
2023-05-22 13:59:10   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
2023-05-22 13:59:10     return fmt.format(record)
2023-05-22 13:59:10   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
2023-05-22 13:59:10     record.message = record.getMessage()
2023-05-22 13:59:10   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
2023-05-22 13:59:10     msg = msg % self.args
2023-05-22 13:59:10 TypeError: not all arguments converted during string formatting
2023-05-22 13:59:10 Call stack:
2023-05-22 13:59:10   File "<string>", line 1, in <module>
2023-05-22 13:59:10   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2023-05-22 13:59:10     exitcode = _main(fd, parent_sentinel)
2023-05-22 13:59:10   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
2023-05-22 13:59:10     return self._bootstrap(parent_sentinel)
2023-05-22 13:59:10   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-05-22 13:59:10     self.run()
2023-05-22 13:59:10   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-05-22 13:59:10     self._target(*self._args, **self._kwargs)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-05-22 13:59:10     target(sockets=sockets)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
2023-05-22 13:59:10     return asyncio.run(self.serve(sockets=sockets))
2023-05-22 13:59:10   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2023-05-22 13:59:10     return loop.run_until_complete(main)
2023-05-22 13:59:10   File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
2023-05-22 13:59:10     self.run_forever()
2023-05-22 13:59:10   File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
2023-05-22 13:59:10     self._run_once()
2023-05-22 13:59:10   File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
2023-05-22 13:59:10     handle._run()
2023-05-22 13:59:10   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2023-05-22 13:59:10     self._context.run(self._callback, *self._args)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-05-22 13:59:10     result = await app(  # type: ignore[func-returns-value]
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-22 13:59:10     return await self.app(scope, receive, send)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
2023-05-22 13:59:10     await super().__call__(scope, receive, send)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
2023-05-22 13:59:10     await self.middleware_stack(scope, receive, send)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-22 13:59:10     await self.app(scope, receive, _send)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-22 13:59:10     await self.app(scope, receive, sender)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-22 13:59:10     await self.app(scope, receive, send)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
2023-05-22 13:59:10     await route.handle(scope, receive, send)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-05-22 13:59:10     await self.app(scope, receive, send)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
2023-05-22 13:59:10     response = await func(request)
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
2023-05-22 13:59:10     raw_response = await run_endpoint_function(
2023-05-22 13:59:10   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-22 13:59:10     return await dependant.call(**values)
2023-05-22 13:59:10   File "/./service_main.py", line 105, in read_presentation
2023-05-22 13:59:10 INFO:     172.18.0.1:35310 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 500 Internal Server Error
2023-05-22 13:59:10     author = get_author(presentation.author_id)
2023-05-22 13:59:10   File "/./circuitbreaker.py", line 159, in wrapper
2023-05-22 13:59:10     return call(function, *args, **kwargs)
2023-05-22 13:59:10   File "/./circuitbreaker.py", line 170, in call
2023-05-22 13:59:10     return func(*args, **kwargs)
2023-05-22 13:59:10   File "/./service_main.py", line 76, in get_author
2023-05-22 13:59:10     logging.warning(">>> Error Connecting:", errc)
2023-05-22 13:59:10 Message: '>>> Error Connecting:'
2023-05-22 13:59:10 Arguments: (ConnectionError(MaxRetryError("HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b8a6b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")),)
2023-05-22 13:59:10 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:10 WARNING:root:
2023-05-22 13:59:11 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:11 WARNING:root:
2023-05-22 13:59:12 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:12 WARNING:root:
2023-05-22 13:59:14 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:14 WARNING:root:
2023-05-22 13:59:15 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:15 WARNING:root:
2023-05-22 13:59:16 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:16 WARNING:root:
2023-05-22 13:59:17 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:17 WARNING:root:
2023-05-22 13:59:18 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:18 WARNING:root:
2023-05-22 13:59:19 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:19 WARNING:root:
2023-05-22 13:59:20 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:20 WARNING:root:
2023-05-22 13:59:21 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:21 WARNING:root:
2023-05-22 13:59:22 WARNING:root:Circuit "get_author" is "closed", failures: 4
2023-05-22 13:59:22 WARNING:root:
2023-05-22 13:59:22 --- Logging error ---
2023-05-22 13:59:22 Traceback (most recent call last):
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
2023-05-22 13:59:22     conn = connection.create_connection(
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
2023-05-22 13:59:22     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-05-22 13:59:22   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-05-22 13:59:22     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-05-22 13:59:22 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-05-22 13:59:22 
2023-05-22 13:59:22 During handling of the above exception, another exception occurred:
2023-05-22 13:59:22 
2023-05-22 13:59:22 Traceback (most recent call last):
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-05-22 13:59:22     httplib_response = self._make_request(
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2023-05-22 13:59:22     conn.request(method, url, **httplib_request_kw)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
2023-05-22 13:59:22     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-05-22 13:59:22   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2023-05-22 13:59:22     self._send_request(method, url, body, headers, encode_chunked)
2023-05-22 13:59:22   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2023-05-22 13:59:22     self.endheaders(body, encode_chunked=encode_chunked)
2023-05-22 13:59:22   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2023-05-22 13:59:22     self._send_output(message_body, encode_chunked=encode_chunked)
2023-05-22 13:59:22   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2023-05-22 13:59:22     self.send(msg)
2023-05-22 13:59:22   File "/usr/lib/python3.10/http/client.py", line 975, in send
2023-05-22 13:59:22     self.connect()
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
2023-05-22 13:59:22     conn = self._new_conn()
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
2023-05-22 13:59:22     raise NewConnectionError(
2023-05-22 13:59:22 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3a24b89630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2023-05-22 13:59:22 
2023-05-22 13:59:22 During handling of the above exception, another exception occurred:
2023-05-22 13:59:22 
2023-05-22 13:59:22 Traceback (most recent call last):
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2023-05-22 13:59:22     resp = conn.urlopen(
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-05-22 13:59:22     retries = retries.increment(
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
2023-05-22 13:59:22     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-05-22 13:59:22 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b89630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:59:22 
2023-05-22 13:59:22 During handling of the above exception, another exception occurred:
2023-05-22 13:59:22 
2023-05-22 13:59:22 Traceback (most recent call last):
2023-05-22 13:59:22   File "/./service_main.py", line 74, in get_author
2023-05-22 13:59:22     response_author = requests.get("http://" + service_author + "/authors/" + str(id))
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
2023-05-22 13:59:22     return request("get", url, params=params, **kwargs)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
2023-05-22 13:59:22     return session.request(method=method, url=url, **kwargs)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2023-05-22 13:59:22     resp = self.send(prep, **send_kwargs)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2023-05-22 13:59:22     r = adapter.send(request, **kwargs)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
2023-05-22 13:59:22     raise ConnectionError(e, request=request)
2023-05-22 13:59:22 requests.exceptions.ConnectionError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b89630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:59:22 
2023-05-22 13:59:22 During handling of the above exception, another exception occurred:
2023-05-22 13:59:22 
2023-05-22 13:59:22 Traceback (most recent call last):
2023-05-22 13:59:22   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
2023-05-22 13:59:22     msg = self.format(record)
2023-05-22 13:59:22   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
2023-05-22 13:59:22     return fmt.format(record)
2023-05-22 13:59:22   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
2023-05-22 13:59:22     record.message = record.getMessage()
2023-05-22 13:59:22   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
2023-05-22 13:59:22     msg = msg % self.args
2023-05-22 13:59:22 TypeError: not all arguments converted during string formatting
2023-05-22 13:59:22 Call stack:
2023-05-22 13:59:22   File "<string>", line 1, in <module>
2023-05-22 13:59:22   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2023-05-22 13:59:22     exitcode = _main(fd, parent_sentinel)
2023-05-22 13:59:22   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
2023-05-22 13:59:22     return self._bootstrap(parent_sentinel)
2023-05-22 13:59:22   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-05-22 13:59:22     self.run()
2023-05-22 13:59:22   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-05-22 13:59:22     self._target(*self._args, **self._kwargs)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-05-22 13:59:22     target(sockets=sockets)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
2023-05-22 13:59:22     return asyncio.run(self.serve(sockets=sockets))
2023-05-22 13:59:22   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2023-05-22 13:59:22     return loop.run_until_complete(main)
2023-05-22 13:59:22   File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
2023-05-22 13:59:22     self.run_forever()
2023-05-22 13:59:22   File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
2023-05-22 13:59:22     self._run_once()
2023-05-22 13:59:22   File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
2023-05-22 13:59:22     handle._run()
2023-05-22 13:59:22   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2023-05-22 13:59:22     self._context.run(self._callback, *self._args)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-05-22 13:59:22     result = await app(  # type: ignore[func-returns-value]
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-22 13:59:22     return await self.app(scope, receive, send)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
2023-05-22 13:59:22     await super().__call__(scope, receive, send)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
2023-05-22 13:59:22     await self.middleware_stack(scope, receive, send)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-22 13:59:22     await self.app(scope, receive, _send)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-22 13:59:22     await self.app(scope, receive, sender)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-22 13:59:22     await self.app(scope, receive, send)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
2023-05-22 13:59:22     await route.handle(scope, receive, send)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-05-22 13:59:22     await self.app(scope, receive, send)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
2023-05-22 13:59:22     response = await func(request)
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
2023-05-22 13:59:22     raw_response = await run_endpoint_function(
2023-05-22 13:59:22   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-22 13:59:22     return await dependant.call(**values)
2023-05-22 13:59:22   File "/./service_main.py", line 105, in read_presentation
2023-05-22 13:59:22 INFO:     172.18.0.1:35316 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 500 Internal Server Error
2023-05-22 13:59:22     author = get_author(presentation.author_id)
2023-05-22 13:59:22   File "/./circuitbreaker.py", line 159, in wrapper
2023-05-22 13:59:22     return call(function, *args, **kwargs)
2023-05-22 13:59:22   File "/./circuitbreaker.py", line 170, in call
2023-05-22 13:59:22     return func(*args, **kwargs)
2023-05-22 13:59:22   File "/./service_main.py", line 76, in get_author
2023-05-22 13:59:22     logging.warning(">>> Error Connecting:", errc)
2023-05-22 13:59:22 Message: '>>> Error Connecting:'
2023-05-22 13:59:22 Arguments: (ConnectionError(MaxRetryError("HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b89630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")),)
2023-05-22 13:59:23 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:23 WARNING:root:
2023-05-22 13:59:23 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:24 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:23 INFO:     172.18.0.1:35322 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:59:24 WARNING:root:
2023-05-22 13:59:25 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:25 WARNING:root:
2023-05-22 13:59:26 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:26 WARNING:root:
2023-05-22 13:59:27 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:27 WARNING:root:
2023-05-22 13:59:28 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:28 WARNING:root:
2023-05-22 13:59:29 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:29 WARNING:root:
2023-05-22 13:59:30 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:30 WARNING:root:
2023-05-22 13:59:31 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:31 WARNING:root:
2023-05-22 13:59:31 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:32 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:32 WARNING:root:Circuit "get_author" is "open", failures: 5
2023-05-22 13:59:32 WARNING:root:
2023-05-22 13:59:33 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:33 WARNING:root:
2023-05-22 13:59:34 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:34 WARNING:root:
2023-05-22 13:59:35 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:35 WARNING:root:
2023-05-22 13:59:36 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:36 WARNING:root:
2023-05-22 13:59:37 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:37 WARNING:root:
2023-05-22 13:59:38 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:38 WARNING:root:
2023-05-22 13:59:39 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:31 INFO:     172.18.0.1:35328 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:59:32 INFO:     172.18.0.1:35334 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:59:39 WARNING:root:
2023-05-22 13:59:40 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:40 WARNING:root:
2023-05-22 13:59:41 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:41 WARNING:root:
2023-05-22 13:59:42 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:42 WARNING:root:
2023-05-22 13:59:43 WARNING:root:Circuit "get_author" is "half_open", failures: 5
2023-05-22 13:59:43 WARNING:root:
2023-05-22 13:59:43 --- Logging error ---
2023-05-22 13:59:43 Traceback (most recent call last):
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
2023-05-22 13:59:43     conn = connection.create_connection(
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 72, in create_connection
2023-05-22 13:59:43     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-05-22 13:59:43   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-05-22 13:59:43     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-05-22 13:59:43 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-05-22 13:59:43 
2023-05-22 13:59:43 During handling of the above exception, another exception occurred:
2023-05-22 13:59:43 
2023-05-22 13:59:43 Traceback (most recent call last):
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-05-22 13:59:43     httplib_response = self._make_request(
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2023-05-22 13:59:43     conn.request(method, url, **httplib_request_kw)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
2023-05-22 13:59:43     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-05-22 13:59:43   File "/usr/lib/python3.10/http/client.py", line 1282, in request
2023-05-22 13:59:43     self._send_request(method, url, body, headers, encode_chunked)
2023-05-22 13:59:43   File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
2023-05-22 13:59:43     self.endheaders(body, encode_chunked=encode_chunked)
2023-05-22 13:59:43   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
2023-05-22 13:59:43     self._send_output(message_body, encode_chunked=encode_chunked)
2023-05-22 13:59:43   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
2023-05-22 13:59:43     self.send(msg)
2023-05-22 13:59:43   File "/usr/lib/python3.10/http/client.py", line 975, in send
2023-05-22 13:59:43     self.connect()
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 205, in connect
2023-05-22 13:59:43     conn = self._new_conn()
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 186, in _new_conn
2023-05-22 13:59:43     raise NewConnectionError(
2023-05-22 13:59:43 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3a24b891b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2023-05-22 13:59:43 
2023-05-22 13:59:43 During handling of the above exception, another exception occurred:
2023-05-22 13:59:43 
2023-05-22 13:59:43 Traceback (most recent call last):
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
2023-05-22 13:59:43     resp = conn.urlopen(
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-05-22 13:59:43     retries = retries.increment(
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
2023-05-22 13:59:43     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-05-22 13:59:43 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b891b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:59:43 
2023-05-22 13:59:43 During handling of the above exception, another exception occurred:
2023-05-22 13:59:43 
2023-05-22 13:59:43 Traceback (most recent call last):
2023-05-22 13:59:43   File "/./service_main.py", line 74, in get_author
2023-05-22 13:59:43     response_author = requests.get("http://" + service_author + "/authors/" + str(id))
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
2023-05-22 13:59:43     return request("get", url, params=params, **kwargs)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
2023-05-22 13:59:43     return session.request(method=method, url=url, **kwargs)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
2023-05-22 13:59:43     resp = self.send(prep, **send_kwargs)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
2023-05-22 13:59:43     r = adapter.send(request, **kwargs)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
2023-05-22 13:59:43     raise ConnectionError(e, request=request)
2023-05-22 13:59:43 requests.exceptions.ConnectionError: HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b891b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-05-22 13:59:43 
2023-05-22 13:59:43 During handling of the above exception, another exception occurred:
2023-05-22 13:59:43 
2023-05-22 13:59:43 Traceback (most recent call last):
2023-05-22 13:59:43   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
2023-05-22 13:59:43     msg = self.format(record)
2023-05-22 13:59:43   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
2023-05-22 13:59:43     return fmt.format(record)
2023-05-22 13:59:43   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
2023-05-22 13:59:43     record.message = record.getMessage()
2023-05-22 13:59:43   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
2023-05-22 13:59:43     msg = msg % self.args
2023-05-22 13:59:43 TypeError: not all arguments converted during string formatting
2023-05-22 13:59:43 Call stack:
2023-05-22 13:59:43   File "<string>", line 1, in <module>
2023-05-22 13:59:43   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2023-05-22 13:59:43     exitcode = _main(fd, parent_sentinel)
2023-05-22 13:59:43   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
2023-05-22 13:59:43     return self._bootstrap(parent_sentinel)
2023-05-22 13:59:43   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-05-22 13:59:43     self.run()
2023-05-22 13:59:43   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-05-22 13:59:43     self._target(*self._args, **self._kwargs)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-05-22 13:59:43     target(sockets=sockets)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
2023-05-22 13:59:43     return asyncio.run(self.serve(sockets=sockets))
2023-05-22 13:59:43   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2023-05-22 13:59:43     return loop.run_until_complete(main)
2023-05-22 13:59:43   File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
2023-05-22 13:59:43     self.run_forever()
2023-05-22 13:59:43   File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
2023-05-22 13:59:43     self._run_once()
2023-05-22 13:59:43   File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
2023-05-22 13:59:43     handle._run()
2023-05-22 13:59:43   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2023-05-22 13:59:43     self._context.run(self._callback, *self._args)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
2023-05-22 13:59:43     result = await app(  # type: ignore[func-returns-value]
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-05-22 13:59:43     return await self.app(scope, receive, send)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
2023-05-22 13:59:43     await super().__call__(scope, receive, send)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
2023-05-22 13:59:43     await self.middleware_stack(scope, receive, send)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-05-22 13:59:43     await self.app(scope, receive, _send)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-05-22 13:59:43     await self.app(scope, receive, sender)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-05-22 13:59:43     await self.app(scope, receive, send)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
2023-05-22 13:59:43     await route.handle(scope, receive, send)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-05-22 13:59:43     await self.app(scope, receive, send)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
2023-05-22 13:59:43     response = await func(request)
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
2023-05-22 13:59:43     raw_response = await run_endpoint_function(
2023-05-22 13:59:43   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
2023-05-22 13:59:43     return await dependant.call(**values)
2023-05-22 13:59:43   File "/./service_main.py", line 105, in read_presentation
2023-05-22 13:59:43     author = get_author(presentation.author_id)
2023-05-22 13:59:43   File "/./circuitbreaker.py", line 159, in wrapper
2023-05-22 13:59:43     return call(function, *args, **kwargs)
2023-05-22 13:59:43   File "/./circuitbreaker.py", line 170, in call
2023-05-22 13:59:43     return func(*args, **kwargs)
2023-05-22 13:59:43   File "/./service_main.py", line 76, in get_author
2023-05-22 13:59:43     logging.warning(">>> Error Connecting:", errc)
2023-05-22 13:59:43 Message: '>>> Error Connecting:'
2023-05-22 13:59:43 Arguments: (ConnectionError(MaxRetryError("HTTPConnectionPool(host='service_author', port=8081): Max retries exceeded with url: /authors/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3a24b891b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")),)
2023-05-22 13:59:43 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:43 INFO:     172.18.0.1:35340 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 500 Internal Server Error
2023-05-22 13:59:43 INFO:     172.18.0.1:35346 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:59:45 INFO:     172.18.0.1:35352 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:59:44 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:44 WARNING:root:
2023-05-22 13:59:45 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:45 WARNING:root:
2023-05-22 13:59:45 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:46 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:46 WARNING:root:
2023-05-22 13:59:47 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:47 WARNING:root:
2023-05-22 13:59:48 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:48 WARNING:root:
2023-05-22 13:59:48 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:49 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:49 WARNING:root:
2023-05-22 13:59:49 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:50 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:50 WARNING:root:
2023-05-22 13:59:50 CRITICAL:root:Circuit OPEN
2023-05-22 13:59:51 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:51 WARNING:root:
2023-05-22 13:59:52 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:52 WARNING:root:
2023-05-22 13:59:53 WARNING:root:Circuit "get_author" is "open", failures: 6
2023-05-22 13:59:53 WARNING:root:
2023-05-22 13:59:54 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 13:59:54 WARNING:root:
2023-05-22 13:59:55 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 13:59:55 WARNING:root:
2023-05-22 13:59:56 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 13:59:56 WARNING:root:
2023-05-22 13:59:57 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 13:59:57 WARNING:root:
2023-05-22 13:59:58 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 13:59:58 WARNING:root:
2023-05-22 13:59:59 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 13:59:59 WARNING:root:
2023-05-22 14:00:00 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 14:00:00 WARNING:root:
2023-05-22 14:00:01 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 14:00:01 WARNING:root:
2023-05-22 13:59:48 INFO:     172.18.0.1:35358 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:59:49 INFO:     172.18.0.1:35364 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 13:59:50 INFO:     172.18.0.1:35370 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 14:00:02 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 14:00:02 WARNING:root:
2023-05-22 14:00:03 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 14:00:03 WARNING:root:
2023-05-22 14:00:04 WARNING:root:Circuit "get_author" is "half_open", failures: 6
2023-05-22 14:00:04 WARNING:root:
2023-05-22 14:00:05 Moore
2023-05-22 14:00:05 INFO:     172.18.0.1:35376 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 14:00:05 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:05 WARNING:root:
2023-05-22 14:00:06 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:06 WARNING:root:
2023-05-22 14:00:07 Moore
2023-05-22 14:00:07 INFO:     172.18.0.1:35384 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 14:00:07 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:07 WARNING:root:
2023-05-22 14:00:08 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:08 WARNING:root:
2023-05-22 14:00:08 Moore
2023-05-22 14:00:08 INFO:     172.18.0.1:35392 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 14:00:09 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:09 WARNING:root:
2023-05-22 14:00:10 Moore
2023-05-22 14:00:10 INFO:     172.18.0.1:35400 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 14:00:10 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:10 WARNING:root:
2023-05-22 14:00:11 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:11 WARNING:root:
2023-05-22 14:00:11 Moore
2023-05-22 14:00:11 INFO:     172.18.0.1:35408 - "GET /presentationsAndAuthor/First%20Presentation HTTP/1.1" 200 OK
2023-05-22 14:00:12 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:12 WARNING:root:
2023-05-22 14:00:13 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:13 WARNING:root:
2023-05-22 14:00:14 WARNING:root:Circuit "get_author" is "closed", failures: 0
2023-05-22 14:00:14 WARNING:root:
